---
attendee-types:
  - name: "Speaker"
    color: "211, 165, 255"
    ticket-titles:
      - "Speaker"

  - name: "Sponsor"
    color: "0, 152, 254"
    ticket-titles:
      - "Monday Support"
      - "Elastic Support"
      - "Akamai Support"
      - "VirtusLab Support"
      - "Grafana Support"
      - "RedHat Support"
      - "TestKube Support"
      - "Monday Support"
      - "Monday Support"
  - name: "Organizer"
    color: "255, 109, 10"
    position: "600,3200"
    ticket-titles:
      - "Organizer"
      - "asd"
  - name: "Volunteer"
    color: "252, 189, 1"
    ticket-titles:
      - "Volunteer"
  - name: "Attendee"
    color: "159, 219, 255"
    background-size: 293
    ticket-titles:
      - "None"
      - "Monday"
      - "Grafana"
      - "Early Bird"
      - "Akamai"
      - "Elastic"
      - "RedHat"
      - "TestKube"
      - "VirtusLab"
      - "Regular"
      - "Last Call"

data:
  - field: "First Name"
    font: "fonts/OpenSans-Bold.ttf"
    size: 250
    position: "330,830"
    color: "20,206,219"
    style: "capitals"
  - field: "Last Name"
    font: "fonts/OpenSans-Bold.ttf"
    size: 170
    position: "330,1220"
    color: "0,0,0"
  # - field: "Title"
  #   font:  "fonts/OpenSans-Regular.ttf"
  #   size: 120
  #   position: "600,1500"
  #   color: "20,206,219"
  # - field: "Company"
  #   font: "fonts/OpenSans-Semibold.ttf"
  #   size: 100
  #   position: "600,1650"
    # color: "0,134,255"
  - field: "Company"
    font: "fonts/OpenSans-Semibold.ttf"
    size: 150
    position: "330,1500"
    color: "0, 134, 255"
fonts:
  - field: "attendee-type"
    font: "fonts/OpenSans-Bold.ttf"
    size: 220
    position: "700,3200"
    # color: "0,255,255"
    color: "255,255,255"
    style: "capitals"
pre-order-data-extend:
  - field: "Company/Organization"
    extends: "Company"
pre-order-data:
  - field: "Job Title"
    font: "fonts/OpenSans-Regular.ttf"
    size: 100
    style: "capitals"
    position: "800, 600"
    color: "207,19,19"
# qr-code:
#   status: "vcard"
#   position: "850, 900"
