---

attendee-types:
  - name: "Speaker"
    color: "211, 165, 255"
    ticket-titles:
      - "100.00% - KCDNL2023SPKR"
  - name: "Sponsor"
    color: "0, 152, 254"
    ticket-titles:
      - "100.00% - KCDAMS23_MULTILAYER_FREE_RRTFS"
      - "100.00% - KCDAMS23_AVISI_FREE_YUHTG"
      - "100.00% - KCDAMS23_CIRCLECI_FREE_UIGHT"
      - "100.00% - KCDAMS23_BUOYANT_FREE_AAXDC"
      - "100.00% - KCDAMS23_ELASTIC_FREE_IJUHY"
      - "100.00% - KCDAMS23_ATCOMP_FREE_RRTFS"
      - "100.00% - KCDAMS23_FULLSTAQ_FREE_ASDCX"
      - "100.00% - KCDAMS23_AKNOSTIC_FREE_UHYGJ"
      - "100.00% - KCDAMS23_FIKAWORKS_FREE_YGVHS"
      - "100.00% - KCDAMS23_ING_FREE_ASDCX"
      - "100.00% - KCDAMS23_REDKUBES_FREE_VGBSD"
      - "100.00% - KCDAMS23_FERMYON_FREE_GYHUT"
      - "100.00% - KCDAMS23_DOIT_FREE_TYGGHF"
      - "100.00% - KCDAMS23_RABO_FREE_BHNJK"
      - "100.00% - KCDAMS23_A1_FREE_ASDCX"
      - "100.00% - KCDAMS23_SPECTROCLOUD_FREE_GTCFS"
      - "100.00% - KCDAMS23_SUSE_FREE_JJHGT"
      - "100.00% - KCDAMS23_MIA_FREE_GYHUT"
      - "100.00% - KCDAMS23_HCS_FREE_RRTFS"
      - "100.00% - KCDAMS23_SOLO.IO_FREE_ASDCX"
      - "100.00% - KCDAMS23_APPVIA_FREE_TYYGH"
      - "100.00% - KCDAMS23_EDB_FREE_JAESR"
      - "100.00% - KCDAMS23_EDGELESS_FREE_HUGYF"

  - name: "Organizer"
    color: "255, 109, 10"
    ticket-titles:
      - "100.00% - KCDAMS23_ORGANIZERS_42"
  - name: "Vip"
    color: "255, 109, 10"
    ticket-titles:
      - "100.00% - KCDAMS23-WILLIAMFRIENDS"
      - "100.00% - KCDAMS_LOVES_DODAMS"
      - "100.00% - KCDAMS23-ANDYFRIENDS"
  - name: "Student"
    color: "159, 219, 255"
    ticket-titles:
      - "75.00% - STUDENTKCD75"
      - "100.00% - KCDAMS_LOVES_DODAMS"
      - "100.00% - KCDAMS23_CODAMFRIENDS"
  - name: "Attendee"
    color: "159, 219, 255"
    ticket-titles:
      - "None"
data:
  - field: "First Name"
    font: "fonts/OpenSans-Bold.ttf"
    size: 140
    position: "100,400"
    color: "207,19,19"
    style: "capitals"
  - field: "Last Name"
    font: "fonts/OpenSans-Bold.ttf"
    size: 80
    position: "100,600"
    color: "0,0,0"
  - field: "Title"
    font:  "fonts/OpenSans-Regular.ttf"
    size: 70
    position: "50,1050"
    color: "207,19,19"
  - field: "Company"
    font: "fonts/OpenSans-Semibold.ttf"
    size: 80
    position: "50,1150"
    color: "20,206,219"
fonts:
  - field: "attendee-type"
    font: "fonts/OpenSans-Bold.ttf"
    size: 140
    position: "270,1610"
    color: "255,255,255"
    style: "capitals"
pre-order-data-extend:
  - field: "Company/Organization"
    extends: "Company"
pre-order-data:
  - field: "Job Title"
    font: "fonts/OpenSans-Regular.ttf"
    size: 50
    style: "capitals"
    position: "100, 700"
    color: "207,19,19"
qr-code:
  status: false
  position: "70, 1300"
