---
size:
  width-mm: 3175
  height-mm: 4763

attendee-types:
  - name: "Speaker"
    color: "211, 165, 255"
    ticket-titles:
      - "Speaker"
  - name: "Sponsor"
    color: "0, 152, 254"
    ticket-titles:
      - "Monday Support"
      - "Elastic Support"
      - "Akamai"
      - "Monday Support"
      - "Monday Support"
      - "Monday Support"
      - "Monday Support"
      - "Monday Support"

  - name: "Organizer"
    color: "255, 109, 10"
    ticket-titles:
      - "Organizer"
      - "asd"
  - name: "Attendee"
    color: "159, 219, 255"
    background-size: 200
    ticket-titles:
      - "None"
      - "Monday"
      - "Grafana"
      - "Early Bird"
      - "Akamai"
      - "Elastic"
      - "RedHat"
      - "TestKube"
      - "VirtusLab"
data:
  - field: "First Name"
    font: "fonts/OpenSans-Bold.ttf"
    size: 120
    position: "180,450"
    color: "20,206,219"
    style: "capitals"
  - field: "Last Name"
    font: "fonts/OpenSans-Bold.ttf"
    size: 80
    position: "180,620"
    color: "0,0,0"
  - field: "Title"
    font:  "fonts/OpenSans-Regular.ttf"
    size: 60
    position: "300,760"
    color: "20,206,219"
  - field: "Company"
    font: "fonts/OpenSans-Semibold.ttf"
    size: 70
    position: "300,820"
    color: "0,134,255"
fonts:
  - field: "attendee-type"
    font: "fonts/OpenSans-Bold.ttf"
    size: 140
    position: "270,1600"
    color: "255,255,255"
    style: "capitals"
pre-order-data-extend:
  - field: "Company/Organization"
    extends: "Company"
pre-order-data:
  - field: "Job Title"
    font: "fonts/OpenSans-Regular.ttf"
    size: 50
    style: "capitals"
    position: "100, 600"
    color: "207,19,19"
# qr-code:
#   status: "vcard"
#   position: "850, 900"
